name: Cypress Test

on: [ push ]

jobs:
  cypress_run:
    runs-on: ubuntu-latest

    steps:
      - name: install MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'reactdb' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'root'  # Required if "mysql user" is empty, default is empty. The root superuser password
      - name: Checkout API Repository
        uses: actions/checkout@v3
        with:
          ref: master
          repository: taavitaivere/NODE-TS-REST-API

      - name: Start Local Server
        run: |
          npm install
          npm start &

      - name: Checkout Frontend Repository
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm install
          start: npm run cypress:open
