name: Cypress Test

on: [push]

jobs:
  cypress_run:
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: master
        repository: taavitaivere/NODE-TS-REST-API

    - name: Start Local Server
      build: npm install
      start: npm start

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cypress run
      uses: cypress-io/github-action@v5

      with:
            build: npm install
            start: npm run cypress:open
